// ─────────────────────────────────────────────────────────────
// КОНФИГУРАЦИЯ ПРОИЗВОДСТВЕННЫХ УЧАСТКОВ
// 8 ресурсов цеха — инициализируются в Firebase при первом запуске
// ─────────────────────────────────────────────────────────────

export const DEFAULT_SHOP_RESOURCES = [
  {
    id: 'bandsaw',
    name: 'Ленточная пила',
    shortName: 'Пила',
    stage: 'cutting_profile',
    hoursPerDay: 8,
    workerCount: 1,
    isLarge: false,
    color: '#3b82f6',
    isAvailable: true,
    notes: 'Только профиль (трубы, уголок, швеллер). Кран при детали > 50 кг (коэф. ×1.4).',
  },
  {
    id: 'plasma',
    name: 'Плазморез',
    shortName: 'Плазма',
    stage: 'cutting_sheet',
    hoursPerDay: 8,
    workerCount: 1,
    isLarge: false,
    color: '#a855f7',
    isAvailable: true,
    notes: 'Только лист (Лист, Раскрой, Фасонка, Пластина). Макс. толщина 20 мм.',
  },
  {
    id: 'weld_lg1',
    name: 'Крупногаб. пост №1',
    shortName: 'Кр.1',
    stage: 'weld_assembly',
    hoursPerDay: 8,
    workerCount: 1,
    isLarge: true,
    color: '#f97316',
    isAvailable: true,
    notes: 'Приоритет — изделия > 3000 мм. Может выполнять и мелкие.',
  },
  {
    id: 'weld_lg2',
    name: 'Крупногаб. пост №2',
    shortName: 'Кр.2',
    stage: 'weld_assembly',
    hoursPerDay: 8,
    workerCount: 1,
    isLarge: true,
    color: '#f97316',
    isAvailable: true,
    notes: 'Приоритет — изделия > 3000 мм. Может выполнять и мелкие.',
  },
  {
    id: 'weld_st1',
    name: 'Стандарт. пост №3',
    shortName: 'Ст.3',
    stage: 'weld_assembly',
    hoursPerDay: 8,
    workerCount: 1,
    isLarge: false,
    color: '#fb923c',
    isAvailable: true,
    notes: 'Оптимален для изделий ≤ 3000 мм. Крупное — аварийно, со снижением скорости.',
  },
  {
    id: 'weld_st2',
    name: 'Стандарт. пост №4',
    shortName: 'Ст.4',
    stage: 'weld_assembly',
    hoursPerDay: 8,
    workerCount: 1,
    isLarge: false,
    color: '#fb923c',
    isAvailable: true,
    notes: 'Оптимален для изделий ≤ 3000 мм. Крупное — аварийно, со снижением скорости.',
  },
  {
    id: 'rolling',
    name: 'Вальцы',
    shortName: 'Вальцы',
    stage: 'rolling',
    hoursPerDay: 8,
    workerCount: 1,
    isLarge: false,
    color: '#06b6d4',
    isAvailable: true,
    notes: 'Гибка листа в цилиндр. Нужна для корпусов Ду300+ (сальники, обечайки). Норма уточняется по факту.',
  },
  {
    id: 'fitters',
    name: 'Слесари',
    shortName: 'Слес.',
    stage: 'fitting',
    hoursPerDay: 32,
    workerCount: 4,
    isLarge: false,
    color: '#22c55e',
    isAvailable: true,
    notes: 'Зачистка + перемещение краном + упаковка. 4 чел., могут работать 2+2.',
  },
  {
    id: 'paint',
    name: 'Покрасочная камера',
    shortName: 'Краска',
    stage: 'painting',
    hoursPerDay: 8,
    workerCount: 1,
    isLarge: false,
    color: '#ef4444',
    isAvailable: true,
    notes: 'Полная загрузка: ~3ч покраска + 2ч сушка = 5ч. Сушка блокирует камеру.',
  },
];

// Маппинг stage → resource IDs (для поиска свободного поста)
export const STAGE_TO_RESOURCES = {
  cutting_profile: ['bandsaw'],
  cutting_sheet:   ['plasma'],
  rolling:         ['rolling'],
  weld_assembly:   ['weld_lg1', 'weld_lg2', 'weld_st1', 'weld_st2'],
  fitting:         ['fitters'],
  painting:        ['paint'],
};
